version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: deploy/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./instance/db:/var/lib/postgresql
  web:
    build: 
      context: .
      dockerfile: deploy/web/Dockerfile
    links:
      - db
    ports:
      - "5000:5000"
    volumes: 
      - ./src/quagen:/app/quagen

  worker:
    build: 
      context: .
      dockerfile: deploy/worker/Dockerfile
    links:
      - db
    volumes: 
      - ./src/quagen:/app/quagen
