version: "3"
services:
  db:
    build:
      context: .
      dockerfile: deploy/docker/db/Dockerfile
    image: quagen-db
    ports:
      - "5432:5432"
    volumes:
      - ./instance/db:/var/lib/postgresql
  node:
    build:
      args:
        QUAGEN_TESTING: "yes"
      context: .
      dockerfile: deploy/docker/node/Dockerfile
    image: quagen-node
    volumes:
      - ./src:/app/src
  web:
    build:
      args:
        QUAGEN_TESTING: "yes"
      context: .
      dockerfile: deploy/docker/web/Dockerfile
    environment:
      QUAGEN_APP_SECRET: "thisisjustatest"
    image: quagen-web
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./src/quagen:/app/quagen
  worker:
    build:
      args:
        QUAGEN_TESTING: "yes"
      context: .
      dockerfile: deploy/docker/worker/Dockerfile
    environment:
      QUAGEN_APP_SECRET: "thisisjustatest"
    image: quagen-worker
    links:
      - db
    volumes:
      - ./src/quagen:/app/quagen
