version: "3"
services:
  db:
    build:
      context: .
      dockerfile: deploy/docker/db/Dockerfile
    image: quagen:db
    ports:
      - "5432:5432"
    volumes:
      - ./instance/db:/var/lib/postgresql
  node:
    build:
      args:
        QUAGEN_TESTING: "yes"
      context: .
      dockerfile: deploy/docker/node/Dockerfile
    image: quagen:node
    volumes:
      - ./src:/app/src
  web:
    build:
      args:
        QUAGEN_TESTING: "yes"
      context: .
      dockerfile: deploy/docker/web/Dockerfile
    command: ["flask", "run"]
    depends_on:
      - db
    environment:
      FLASK_ENV: "development"
      QUAGEN_APP_SECRET: "thisisjustatest"
    image: quagen:web
    ports:
      - "5000:5000"
    volumes:
      - ./src/quagen:/app/quagen
  worker:
    build:
      args:
        QUAGEN_TESTING: "yes"
      context: .
      dockerfile: deploy/docker/worker/Dockerfile
    command: ["./reloader.sh"]
    depends_on:
      - db
    environment:
      QUAGEN_APP_SECRET: "thisisjustatest"
    image: quagen:worker
    volumes:
      - ./src/quagen:/app/quagen
  migrator:
    command: ["python", "quagen/migrator.py"]
    depends_on:
      - db
    environment:
      QUAGEN_APP_SECRET: "thisisjustatest"
    image: quagen:worker
    volumes:
      - ./src/quagen:/app/quagen
