apiVersion: v1
kind: Service
metadata:
  name: quagen-web
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: quagen-web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quagen-web
spec:
  selector:
    matchLabels:
      app: quagen-web
  replicas: 3
  template:
    metadata:
      labels:
        app: quagen-web
    spec:
      containers:
      - name: quagen-web
        image: seekely/quagen-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000      
