name: ci
on: [push]
jobs:
    python-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1
              
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Installing Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r requirements-dev.txt

            - name: Run lint
              run: |
                pylint_runner -v

            - name: Run tests
              run: |
                PYTHONPATH=src python -m pytest tests -W ignore::DeprecationWarning

    js-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1
              
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 10.16.2

            - name: Installing Node dependencies
              run: npm install

            - name: Run lint
              run: |
                npm run lint

            - name: Run tests
              run: |
                npm test

