name: ci
on: [push]
jobs:
    python-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Build containers
              run: |
                docker-compose build
              
            - name: Run lint
              run: |
                bin/lint_python

            - name: Run tests
              run: |
                bin/test_unit_python && bin/test_profile_python

    js-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Build containers
              run: |
                docker-compose build
              
            - name: Run lint
              run: |
                bin/lint_js

            - name: Run tests
              run: |
                bin/test_unit_js

